Fail immediately in case of failure in most of the scripts
This is done by setting "set -e" at the top of the scripts targetted.
postgres_get_port does not work yet with that though.

diff --git a/bin/pg_binarchive b/bin/pg_binarchive
--- a/bin/pg_binarchive
+++ b/bin/pg_binarchive
@@ -10,6 +10,9 @@
 #	features like pg_upgrade when testing.
 #--------------------------------------------------------------------------
 
+# Immediately leave in case of failure
+set -e
+
 # Create stable repository if it does not exist yet
 if [ ! -d $HOME_STABLE_BIN ]
 then
