Avoid use of unassigned variables in scripts
This will help to avoid particularly unwanted "rm -rf /" commands where
the base path is not set, ripping out the whole tree.

diff --git a/bin/pg_binarchive b/bin/pg_binarchive
--- a/bin/pg_binarchive
+++ b/bin/pg_binarchive
@@ -10,8 +10,9 @@
 #	features like pg_upgrade when testing.
 #--------------------------------------------------------------------------
 
-# Immediately leave in case of failure
-set -e
+# Immediately leave in case of failure and avoid using unassigned
+# variables.
+set -eu
 
 # Create stable repository if it does not exist yet
 if [ ! -d "$HOME_STABLE_BIN" ]; then
diff --git a/bin/ssl_key_generate b/bin/ssl_key_generate
--- a/bin/ssl_key_generate
+++ b/bin/ssl_key_generate
@@ -5,8 +5,9 @@
 #	Copyright (c) 2010-2017, Michael Paquier
 #--------------------------------------------------------------------------
 
-# Immediately leave in case of failure
-set -e
+# Immediately leave in case of failure and avoid using unassigned
+# variables.
+set -eu
 
 which openssl > /dev/null 2>&1
 if [ $? != 0 ]; then
