Move all the compilation utilities into the unique pg_compile
pg_compile integrates now options to copy source code to another folder and
execute vpath and normal installations. The following options are added:
- i to define an input folder containing source code
- o to define an output folder used for compilation
- n flag to to a normal installation
- v flag to do a vpath installation
In the case of a normal installation, the code is copied from input to output
then compiled. For a VPATH, a new output folder is created and the configure
located in input folder is used for configuration.
In consequence, utilities makepostgres and makevpath are removed.

diff --git a/bin/pg_compile b/bin/pg_compile
--- a/bin/pg_compile
+++ b/bin/pg_compile
@@ -1,9 +1,11 @@
 #!/bin/sh
 #--------------------------------------------------------------------------
 # pg_compile
-#	Compile PostgreSQL or Postgres-XC code
+#	Copy and compile PostgreSQL or Postgres-XC code
 #	Copyright (c) 2010-2012, Michael Paquier
-#	Run regressions if necessary or enforce debug flag
+#
+#	The code used for compilation is a copy of an original code.
+#	Run regressions if necessary or enforce debug flag.
 #--------------------------------------------------------------------------
 
 # Take and check options
@@ -11,6 +13,12 @@ EXPECTED_ARGS=0
 FLAG_DEBUG=0
 FLAG_REGRESS=0
 FLAG_PATH=0
+# VPATH and code copy flags
+FLAG_INPUT_FOLDER=0
+FLAG_OUTPUT_FOLDER=0
+FLAG_VPATH=0
+FLAG_NORMAL=0
+FLAG_COPY_ONLY=0
 
 # Show help
 show_help()
@@ -19,15 +27,21 @@ show_help()
 	echo "Usage: `basename $0` [OPTION]..."
 	echo " "
 	echo "Options:"
-	echo "  -d                  Compile with debug flag"
-	echo "  -h                  Show this help"
-	echo "  -p PATH             Define installation folder"
-	echo "  -r                  Run regressions"
+	echo "  -d       Compile with debug flag"
+	echo "  -h       Show this help"
+	echo "  -p PATH  Define installation folder"
+	echo "  -r       Run regressions"
+	echo " "
+	echo "Code copy for installation:"
+	echo "  -i PATH  Original code folder (input)"
+	echo "  -o PATH  install folder (output)"
+	echo "  -n       Normal installation"
+	echo "  -v       VPATH installation"
 	exit $ERROR_NUM
 }
 
 #Treat options
-while getopts 'dhp:r' OPTION
+while getopts 'dhi:no:p:rv' OPTION
 do
 	case $OPTION in
 	d)	# Enforce debug flag
@@ -37,6 +51,20 @@ do
 	h)	# Help
 		show_help 0
 		;;
+	i)	# Folder where to install code with vpath
+		FLAG_INPUT_FOLDER=1
+		USER_INPUT_FOLDER="$OPTARG"
+		EXPECTED_ARGS=$(($EXPECTED_ARGS + 2))
+		;;
+	n)	# Normal installation flag
+		FLAG_NORMAL=1
+		EXPECTED_ARGS=$(($EXPECTED_ARGS + 1))
+		;;
+	o)	# Folder where original code is located -- vpath install
+		FLAG_OUTPUT_FOLDER=1
+		USER_OUTPUT_FOLDER="$OPTARG"
+		EXPECTED_ARGS=$(($EXPECTED_ARGS + 2))
+		;;
 	p)	# Installation folder
 		FLAG_PATH=1
 		USER_INSTALL_FOLDER="$OPTARG"
@@ -44,6 +72,10 @@ do
 		;;
 	r)	# Run regressions
 		FLAG_REGRESS=1
+		EXPECTED_ARGS=$(($EXPECTED_ARGS + 1))
+		;;
+	v)	# VPATH flag
+		FLAG_VPATH=1
 		EXPECTED_ARGS=$(($EXPECTED_ARGS + 1))
 		;;
 	?)	# Help
@@ -58,6 +90,42 @@ then
 	show_help 1
 fi
 
+# Check option compatibility
+# Leave an error if both normal and vpath installation are wanted
+if [ "$FLAG_VPATH" == 1 -a "$FLAG_NORMAL" == 1 ]
+then
+	echo "Cannot do VPATH and normal installation at the same time"
+	exit 1
+fi
+# Leave error if input and output are precised without an installation flag
+if [ "$FLAG_OUTPUT_FOLDER" == 1 -a "$FLAG_VPATH" == 0 -a "$FLAG_NORMAL" == 0 ]
+then
+	echo "Cannot define output folder without installation flag activated"
+	exit 1
+fi
+if [ "$FLAG_INPUT_FOLDER" == 1 -a "$FLAG_VPATH" == 0 -a "$FLAG_NORMAL" == 0 ]
+then
+	echo "Cannot define input folder without installation flag activated"
+	exit 1
+fi
+
+# Set input folder value
+if [ "$FLAG_INPUT_FOLDER" == 1 ]
+then
+	PSQL_INPUT_FOLDER=$USER_INPUT_FOLDER
+else
+	PSQL_INPUT_FOLDER=$HOME/git/postgres
+	echo "Using default input folder $PSQL_INPUT_FOLDER"
+fi
+# Set output folder value
+if [ "$FLAG_OUTPUT_FOLDER" == 1 ]
+then
+	PSQL_OUTPUT_FOLDER=$USER_OUTPUT_FOLDER
+else
+	PSQL_OUTPUT_FOLDER=$HOME/make
+	echo "Using default output folder $PSQL_OUTPUT_FOLDER"
+fi
+
 # Define installation folder
 if [ "$FLAG_PATH" == 1 ]
 then
@@ -67,15 +135,53 @@ else
 	echo "Using default installation folder $PSQL_INSTALL_FOLDER"
 fi
 
-# Install Postgres-XC binaries
-if [ "$FLAG_DEBUG" == 1 ]
+# If normal or vpath install flags are activated, we need to copy the code first
+if [ "$FLAG_VPATH" == 1 -o "$FLAG_NORMAL" == 1 ]
 then
-	./configure --prefix=$PSQL_INSTALL_FOLDER --enable-depend --enable-debug --disable-rpath --enable-cassert --with-libxml CFLAGS="-DG"
+	# Clean up the output folder if it already exists
+	if [ -d $PSQL_OUTPUT_FOLDER ]
+	then
+		rm -rf $PSQL_OUTPUT_FOLDER
+		echo "Deleting existing output folder $PSQL_OUTPUT_FOLDER"
+	fi
+
+	# If VPATH installation is activated, we need to call configure currently
+	# located in the input folder directly in the output folder
+	if [ "$FLAG_VPATH" == 1 ]
+	then
+		# Case of a VPATH installation
+
+		# Then move in the output folder and launch configure in input folder
+		mkdir $PSQL_OUTPUT_FOLDER
+		cd $PSQL_OUTPUT_FOLDER
+		CONFIGURE_CALL_FOLDER=$PSQL_INPUT_FOLDER
+	else
+		# Case of a normal installation, here calling configure from the local
+		# folder is enough. But first copy code.
+		cp -r $PSQL_INPUT_FOLDER $PSQL_OUTPUT_FOLDER
+		cd $PSQL_OUTPUT_FOLDER
+		CONFIGURE_CALL_FOLDER="."
+	fi
+
+	# Configure Postgres install folder
+	if [ "$FLAG_DEBUG" == 1 ]
+	then
+		$CONFIGURE_CALL_FOLDER/configure --prefix=$PSQL_INSTALL_FOLDER --enable-depend --enable-debug --disable-rpath --enable-cassert --with-libxml CFLAGS="-DG"
+	else
+		$CONFIGURE_CALL_FOLDER/configure --prefix=$PSQL_INSTALL_FOLDER --enable-depend --enable-debug --disable-rpath --enable-cassert --with-libxml
+	fi
 else
-	./configure --prefix=$PSQL_INSTALL_FOLDER --enable-depend --enable-debug --disable-rpath --enable-cassert --with-libxml
+	# We do here a normal install, so do not worry about anything with code copy
+	if [ "$FLAG_DEBUG" == 1 ]
+	then
+		./configure --prefix=$PSQL_INSTALL_FOLDER --enable-depend --enable-debug --disable-rpath --enable-cassert --with-libxml CFLAGS="-DG"
+	else
+		./configure --prefix=$PSQL_INSTALL_FOLDER --enable-depend --enable-debug --disable-rpath --enable-cassert --with-libxml
+	fi
 fi
 
-# Compile
+# Compile, by being here we certify that we are already in the compilation
+# folder
 make
 
 # Run regressions if necessary
