Check if files listed in FILES are present in configuration
This is used to prevent mistakes in a single configuration set.

diff --git a/bin/spatch b/bin/spatch
--- a/bin/spatch
+++ b/bin/spatch
@@ -124,16 +124,23 @@ parse_list_files()
 
 	if [ ! -f $FILE_LIST ]
 	then
-		echo "FILES is missing for configuration $SPATCH_CONF."
+		echo "FILES is missing for configuration \"$SPATCH_CONF\"."
 		echo "This file is needed with the list of file entries to link."
 		exit 1
 	fi
 
 	# Complete list of files
-	for entry in `cat $CONFIG_FOLDER/$SPATCH_CONF/FILES`
+	for entry in `cat $FILE_LIST`
 	do
 		FILES[$i]=`echo $entry | cut -d ':' -f 1`
 		LINKS[$i]=`echo $entry | cut -d ':' -f 2`
+		# Sanity checks
+		if [ ! -f $CONFIG_FOLDER/$SPATCH_CONF/${FILES[$i]} ]
+		then
+			file=${FILES[$i]}
+			echo "\"$file\" does not exist in configuration \"$SPATCH_CONF\" but it is listed in $FILE_LIST."
+			exit 1
+		fi
 		i=`expr $i + 1`
 	done
 }
@@ -158,7 +165,7 @@ command_confnew()
 	fi
 
 	# Now create the new configuration
-	echo "Created new configuration $NEW_CONF"
+	echo "Created new configuration \"$NEW_CONF\""
 	cp -r $CONFIG_FOLDER/default $CONFIG_FOLDER/$NEW_CONF
 }
 
@@ -177,7 +184,7 @@ command_confrm()
 	# Block removal of configuration default
 	if [ $OLD_CONF = "default" -o $OLD_CONF = "example" ]
 	then
-		echo "Cannot remove configuration $OLD_CONF"
+		echo "Cannot remove configuration \"$OLD_CONF\""
 		exit 1
 	fi
 
@@ -189,7 +196,7 @@ command_confrm()
 	fi
 
 	# Now remove the configuration
-	echo "Remove configuration $OLD_CONF"
+	echo "Remove configuration \"$OLD_CONF\""
 	rm -r $CONFIG_FOLDER/$OLD_CONF
 }
 
@@ -265,7 +272,7 @@ command_confreset()
 		echo "No current configuration found, hence leaving"
 		exit 0
 	else
-		echo "Removing configuration $CURRENT_CONF"
+		echo "Removing configuration \"$CURRENT_CONF\""
 	fi
 
 	# Remove all the links if they exit
@@ -275,7 +282,7 @@ command_confreset()
 		#FILE=~/.bash_alias_extra
 		if [[ -h $HOME/$link ]]
 		then
-			echo "Removed link $HOME/$link"
+			echo "Removed link \"$HOME/$link\""
 			rm $HOME/$link
 		fi
 	done
@@ -312,7 +319,7 @@ command_conf()
 	# Check presence of new configuration
 	if [ ! -d $CONFIG_FOLDER/$NEW_CONF ]
 	then
-		echo "Invalid configuration $NEW_CONF, no configuration files"
+		echo "Invalid configuration \"$NEW_CONF\", no configuration files"
 		exit 1
 	fi
 
@@ -328,7 +335,7 @@ command_conf()
 	for file in ${FILES[@]}
 	do
 		link=${LINKS[$i]}
-		echo "Linking $link to $CONFIG_FOLDER/$NEW_CONF/$file"
+		echo "Linking \"$link\" to \"$CONFIG_FOLDER/$NEW_CONF/$file\""
 		ln -s $CONFIG_FOLDER/$NEW_CONF/$file $HOME/$link
 		i=`expr $i + 1`
 	done
@@ -355,9 +362,9 @@ command_env()
 	ERROR=$?
 	if [ "$ERROR" = 0 ]
 	then
-		echo "Switched to environment $NEW_ENV"
+		echo "Switched to environment \"$NEW_ENV\""
 	else
-		echo "Incorrect environment $NEW_ENV"
+		echo "Incorrect environment \"$NEW_ENV\""
 	fi
 }
 
