Finish implementation of spatch for dynamic configuration
It is possible to set new configurations and even reset them.

diff --git a/bin/spatch b/bin/spatch
--- a/bin/spatch
+++ b/bin/spatch
@@ -14,8 +14,13 @@ NUM_ARGS=$#
 
 # Default parameters
 CONFIG_FOLDER=$HOME/.spatch.d/ # General config folder
-CURRENT_CONFIG=$CONFIG_FOLDER/current # Where is stored current config
+CURRENT_CONFIG_FILE_MARKER=$CONFIG_FOLDER/current # Where is stored current config
 VERSION="spatch version 1.0"
+
+# List of files
+FILES[0]=gitconfig_extra
+FILES[1]=bash_extra
+FILES[2]=bash_alias_extra
 
 show_help ()
 {
@@ -26,8 +31,9 @@ show_help ()
 	echo "   conf-list  List possible configuration sets";
 	echo "   conf-desc  Describe given configuration set";
 	echo "   conf-show  Show current configuration set";
-	echo "   env        Switch environment"
-	echo "   env-list   List available environments"
+	echo "   conf-reset Reset current configuration";
+	echo "   env        Switch environment";
+	echo "   env-list   List available environments";
 }
 
 # Check number of arguments for command
@@ -73,6 +79,13 @@ check_args ()
 		then
 			ERROR=1
 		fi
+	elif [ "$COMMAND" = "conf-reset" ]
+	then
+		# No argument needed here
+		if [ "$NUM_ARGS" -gt 1 ]
+		then
+			ERROR=1
+		fi
 	elif [ "$COMMAND" = "conf-show" ]
 	then
 		# Here we do not need extra arguments
@@ -113,11 +126,7 @@ command_confdesc ()
 	# If name is empty, fallback to current
 	if [ -z "$CONFIG_NAME" ]
 	then
-		# Be sure that current config exists
-		if [  -f "$CURRENT_CONFIG" ]
-		then
-			CONFIG_NAME=`cat $CURRENT_CONFIG`
-		fi
+		CONFIG_NAME=`get_current_conf_name`
 	fi
 
 	# Error if still empty
@@ -148,20 +157,83 @@ command_confdesc ()
 	echo `cat $DESC_FILE`
 }
 
+# Execute command conf-reset
+command_confreset ()
+{
+	# Get current configuration name and check existence
+	CURRENT_CONF=`get_current_conf_name`
+
+	if [ -z $CURRENT_CONF ]
+	then
+		echo "No configuration found, forcing reset"
+	else
+		echo "Removing configuration $CURRENT_CONF"
+	fi
+
+	# Remove all the files if they exit
+	for file in ${FILES[@]}
+	do
+		if [ -f $HOME/.$file ]
+		then
+			echo "Removed file $file"
+			rm $HOME/.$file
+		fi
+	done
+
+	# Delete current configuration file marker
+	if [ -f $CURRENT_CONFIG_FILE_MARKER ]
+	then
+		rm $CURRENT_CONFIG_FILE_MARKER
+	fi
+}
+
+# Get current configuration name
+get_current_conf_name ()
+{
+	# Be sure that current config exists or return null
+	if [  -f "$CURRENT_CONFIG_FILE_MARKER" ]
+	then
+		echo `cat $CURRENT_CONFIG_FILE_MARKER`
+	fi
+}
+
 # Execute command conf
 command_conf ()
 {
-	echo "new configuration: $1"
-	echo "Not implemented yet"
-	exit 1
+	NEW_CONF=$1
+
+	# Check presence of new configuration
+	if [ ! -d $CONFIG_FOLDER/$NEW_CONF ]
+	then
+		echo "Invalid configuration $NEW_CONF, no configuration files"
+		exit 1
+	fi
+
+	# Then remove old configuration
+	command_confreset
+
+	# Link to the new objects
+	for file in ${FILES[@]}
+	do
+		echo "Linking $HOME/.$file to $CONFIG_FOLDER/$NEW_CONF/$file"
+		ln -s $CONFIG_FOLDER/$NEW_CONF/$file $HOME/.$file
+	done
+
+	# Create current marker
+	echo $NEW_CONF > $CURRENT_CONFIG_FILE_MARKER
 }
 
 # Execute command conf-show
 command_confshow ()
 {
-	echo "current configuration"
-	echo "Not implemented yet"
-	exit 1
+	CONF_NAME=`get_current_conf_name`
+
+	if [ -z $CONF_NAME ]
+	then
+		echo "No configuration available"
+	else
+		echo "$CONF_NAME"
+	fi
 }
 
 # Execute command env
@@ -222,6 +294,10 @@ elif [ "$COMMAND_TYPE" = "conf-desc" ]
 then
 	# Show description of given configuration
 	command_confdesc $2
+elif [ "$COMMAND_TYPE" = "conf-reset" ]
+then
+	# Reset current configuration
+	command_confreset
 elif [ "$COMMAND_TYPE" = "conf-show" ]
 then
 	command_confshow
