Minimize output data of start_cluster
This makes the script for user-friendly.

diff --git a/bin/start_cluster b/bin/start_cluster
--- a/bin/start_cluster
+++ b/bin/start_cluster
@@ -93,12 +93,7 @@ do
 done
 
 #Kill all the processes that may remain
-#in the most atrocious way possible as they meritated it
-#OK this is not very clean...
-echo "Take out Postgres-XC processes"
-kill -9 `ps ux | grep "bin/gtm" | cut -d " " -f 2-3`
-killall postgres gtm psql
-sleep 2
+menage
 
 #Check log folder
 echo "Creating log folder"
@@ -123,7 +118,7 @@ done
 echo "Clean up data folders"
 for folder in $GTM_DATA $LOG_DATA ${COORD_DATAS[@]} ${COORD_SLAVE_DATAS[@]} ${COORD_SLAVE_ARCHIVE[@]} ${DN_DATAS[@]} ${DN_SLAVE_DATAS[@]} ${DN_SLAVE_ARCHIVE[@]}
 do
-	rm -r $folder/*
+	rm -r $folder/* > /dev/null 2>&1
 done
 sleep 1
 
@@ -133,17 +128,40 @@ sleep 1
 echo "Initializing PGXC nodes"
 for i in $(seq 1 $NUM_DATANODES)
 do
-	$PSQL_BIN/initdb --nodename dn$i -D ${DN_DATAS[$i]}
+	echo "Initializing Datanode $i"
+	$PSQL_BIN/initdb --nodename dn$i -D ${DN_DATAS[$i]} > /dev/null 2>&1
+
+	ERROR=$?
+	if [ "$ERROR" != 0 ]
+	then
+		echo "Error while initializing Datanode $i"
+		exit 1
+	fi
 done
 for i in $(seq 1 $NUM_COORDS)
 do
-	$PSQL_BIN/initdb --nodename coord$i -D ${COORD_DATAS[$i]}
+	echo "Initializing Coordinator $i"
+	$PSQL_BIN/initdb --nodename coord$i -D ${COORD_DATAS[$i]} > /dev/null 2>&1
+
+	ERROR=$?
+	if [ "$ERROR" != 0 ]
+	then
+		echo "Error while initializing Coordinator $i"
+		exit 1
+	fi
 done
 
 #copy all configuration files to remote machin
-echo "Copy of configuration files"
+echo "Initializing GTM"
 #Create an empty GTM conf file and add host/port data
-$PSQL_BIN/initgtm -D $GTM_DATA -Z gtm
+$PSQL_BIN/initgtm -D $GTM_DATA -Z gtm > /dev/null 2>&1
+
+ERROR=$?
+if [ "$ERROR" != 0 ]
+then
+	echo "Error while initializing GTM"
+	exit 1
+fi
 #Add the port number for GTM
 echo "port = $GTM_PORT" >> $GTM_DATA/gtm.conf
 
@@ -256,7 +274,7 @@ done
 sleep 2
 
 #Initialize Coordinators with cluster data
-echo "initializing Coordinators..."
+echo "Initializing Coordinators with cluster data"
 for i in $(seq 1 $NUM_COORDS)
 do
 	#Datanode connection info
@@ -264,7 +282,7 @@ do
 	do
 		NODE_NAME=dn$j
 		NODE_PORT=${DN_PORTS[$j]}
-		$PSQL_BIN/psql -p ${COORD_PORTS[$i]} -c "CREATE NODE $NODE_NAME WITH (HOST = 'localhost', type = 'datanode', PORT = $NODE_PORT);" postgres
+		$PSQL_BIN/psql -p ${COORD_PORTS[$i]} -c "CREATE NODE $NODE_NAME WITH (HOST = 'localhost', type = 'datanode', PORT = $NODE_PORT);" postgres > /dev/null 2>&1
 	done
 	#Other Coordinator info
 	for j in $(seq 1 $NUM_COORDS)
@@ -275,10 +293,10 @@ do
 		fi
 		NODE_NAME=coord$j
 		NODE_PORT=${COORD_PORTS[$j]}
-		$PSQL_BIN/psql -p ${COORD_PORTS[$i]} -c "CREATE NODE $NODE_NAME WITH (HOST = 'localhost', type = 'coordinator', PORT = $NODE_PORT);" postgres
+		$PSQL_BIN/psql -p ${COORD_PORTS[$i]} -c "CREATE NODE $NODE_NAME WITH (HOST = 'localhost', type = 'coordinator', PORT = $NODE_PORT);" postgres > /dev/null 2>&1
 	done
 	#reload data
-	$PSQL_BIN/psql -p ${COORD_PORTS[$i]} -c "SELECT pgxc_pool_reload();" postgres
+	$PSQL_BIN/psql -p ${COORD_PORTS[$i]} -c "SELECT pgxc_pool_reload();" postgres > /dev/null 2>&1
 done
 
 # Launch backups for slave nodes
